### Invalid signup request test
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com"
}

### Invalid login request test
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "gmail.com"
}

### Valid signup request test
PUT http://localhost:3000/users/fyp/1 HTTP/1.1
content-type: application/json

{

	"role": "hipster",
	"desc": "webdev112sdfasdf233",
	"photoUrl":"dsfasdfsa.com"
}

### Valid login request test
POST http://localhost:3000/auth/login/?user_id=1 HTTP/1.1
content-type: application/json

{
	"email": "msulthanmazaya@gmail.com",
	"password": "Patriot*100"
}