### Invalid signup request test
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com"
}

### Invalid login request test
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "gmail.com"
}

### Valid signup request test
POST https://api.tecinternship2021.com/auth/signup HTTP/1.1
content-type: application/json

{

	"email": "testa@gmail.com",
	"password": "a"
}

### Valid login request test
POST https://api.tecinternship2021.com/auth/login HTTP/1.1
content-type: application/json

{
	"email": "testa@gmail.com",
	"password": "a"
}