### Get all transaction
GET http://localhost:3000/transaction/417c5934-04e3-4233-af79-0049046c4a29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZmllZCI6ZmFsc2UsImFkbWluIjpmYWxzZSwibmFtZSI6bnVsbCwiZmFrdWx0YXMiOm51bGwsImVtYWlsIjoibXN1bHRoYW5tYXpheWFAZ21haWwuY29tIiwibmltIjpudWxsLCJpZCI6MSwiaWF0IjoxNjMwNDYzMDc5LCJleHAiOjE2MzA2MzU4Nzl9.BQbM2qCY_VoHOFX0SbbHtxNMgylnSrSTcqWNrsyMzTY

### Valid signup request test
POST http://localhost:3000/transaction HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZmllZCI6ZmFsc2UsImFkbWluIjpmYWxzZSwibmFtZSI6bnVsbCwiZmFrdWx0YXMiOm51bGwsImVtYWlsIjoibXN1bHRoYW5tYXpheWFAZ21haWwuY29tIiwibmltIjpudWxsLCJpZCI6MSwiaWF0IjoxNjMwNDYzMDc5LCJleHAiOjE2MzA2MzU4Nzl9.BQbM2qCY_VoHOFX0SbbHtxNMgylnSrSTcqWNrsyMzTY

{
    "photoUrl":"https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80",
    "metode":"test",
    "media":"BNI",
    "nominal":"124234",
    "uniqueIdentifier":"1",
    "noRekening":"3413431412",
    "pemilikRekening":"Nana",
    "usersEmail":[
        "msulthanmazaya@gmail.com",
        "satu@mail.com",
        "dua@mail.com",
        "tiga@mail.com",
        "empat@mail.com"
    ]
}

### Delete

DELETE http://localhost:3000/transaction/044d1a75-41aa-4695-b687-7711ab26a3de HTTP/1.1